### ISSUE TITLE
能否加个功能

### ISSUE THREAD

**Issue by Zheisbug** [1150037361/SpringScan#1]
场景

没登录没授权的时候是扫不出“/actuator/env”

如果登录后(授权后)可以再扫一次

比如Authorization、Token之类的

**Comment by M4ng0sec** [comment]
可以判断下请求包，是否新增这些授权信息，如果新增的话可以再扫描一次。

**Comment by 1150037361** [comment]
这个插件主要是修改URL信息，当你请求头有授权信息时会自动加上的，而且你每次请求都会进行扫描，所以是会自动带上授权信息的

**Comment by 1150037361** [comment]
> 可以判断下请求包，是否新增这些授权信息，如果新增的话可以再扫描一次。

可以看下新的版本，

**Comment by M4ng0sec** [comment]
OK！我再试试新的。

**Comment by M4ng0sec** [comment]
加个开关按钮吧~

**Comment by 1150037361** [comment]
> 加个开关按钮吧~

下个版本会加，还有更多功能
![image](https://github.com/1150037361/SpringScan/assets/66943818/260398c7-470f-4445-9511-bc4480ef3d38)

**Comment by 1150037361** [comment]
目前还在测试
